"""init schema (teams/players/stats/games)

Revision ID: fca8b58c22a2
Revises: c3528a507434
Create Date: 2025-08-18 21:42:25.398617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fca8b58c22a2'
down_revision: Union[str, None] = 'c3528a507434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.String(), nullable=True),
    sa.Column('games_behind', sa.String(), nullable=True),
    sa.Column('streak', sa.String(), nullable=True),
    sa.Column('home_record', sa.String(), nullable=True),
    sa.Column('away_record', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_index(op.f('ix_teams_team_code'), 'teams', ['team_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_code', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('stadium', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_away_team_id'), 'games', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_date'), 'games', ['date'], unique=False)
    op.create_index(op.f('ix_games_game_code'), 'games', ['game_code'], unique=True)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('bat_hand', sa.String(), nullable=True),
    sa.Column('throw_hand', sa.String(), nullable=True),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_player_code'), 'players', ['player_code'], unique=True)
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('hitter_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_code', sa.String(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('g', sa.Integer(), nullable=True),
    sa.Column('pa', sa.Integer(), nullable=True),
    sa.Column('ab', sa.Integer(), nullable=True),
    sa.Column('r', sa.Integer(), nullable=True),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('sb', sa.Integer(), nullable=True),
    sa.Column('cs', sa.Integer(), nullable=True),
    sa.Column('bb', sa.Integer(), nullable=True),
    sa.Column('hbp', sa.Integer(), nullable=True),
    sa.Column('so', sa.Integer(), nullable=True),
    sa.Column('avg', sa.String(), nullable=True),
    sa.Column('obp', sa.String(), nullable=True),
    sa.Column('slg', sa.String(), nullable=True),
    sa.Column('ops', sa.String(), nullable=True),
    sa.Column('war', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_code', 'player_id', name='uq_hitter_season_player')
    )
    op.create_index(op.f('ix_hitter_stats_player_id'), 'hitter_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_hitter_stats_season_code'), 'hitter_stats', ['season_code'], unique=False)
    op.create_index(op.f('ix_hitter_stats_team_id'), 'hitter_stats', ['team_id'], unique=False)
    op.create_table('pitcher_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_code', sa.String(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('g', sa.Integer(), nullable=True),
    sa.Column('gs', sa.Integer(), nullable=True),
    sa.Column('w', sa.Integer(), nullable=True),
    sa.Column('l', sa.Integer(), nullable=True),
    sa.Column('sv', sa.Integer(), nullable=True),
    sa.Column('hld', sa.Integer(), nullable=True),
    sa.Column('ip_outs', sa.Integer(), nullable=True),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('bb', sa.Integer(), nullable=True),
    sa.Column('hbp', sa.Integer(), nullable=True),
    sa.Column('so', sa.Integer(), nullable=True),
    sa.Column('r', sa.Integer(), nullable=True),
    sa.Column('er', sa.Integer(), nullable=True),
    sa.Column('era', sa.String(), nullable=True),
    sa.Column('whip', sa.String(), nullable=True),
    sa.Column('war', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_code', 'player_id', name='uq_pitcher_season_player')
    )
    op.create_index(op.f('ix_pitcher_stats_player_id'), 'pitcher_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_pitcher_stats_season_code'), 'pitcher_stats', ['season_code'], unique=False)
    op.create_index(op.f('ix_pitcher_stats_team_id'), 'pitcher_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitcher_stats_team_id'), table_name='pitcher_stats')
    op.drop_index(op.f('ix_pitcher_stats_season_code'), table_name='pitcher_stats')
    op.drop_index(op.f('ix_pitcher_stats_player_id'), table_name='pitcher_stats')
    op.drop_table('pitcher_stats')
    op.drop_index(op.f('ix_hitter_stats_team_id'), table_name='hitter_stats')
    op.drop_index(op.f('ix_hitter_stats_season_code'), table_name='hitter_stats')
    op.drop_index(op.f('ix_hitter_stats_player_id'), table_name='hitter_stats')
    op.drop_table('hitter_stats')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_index(op.f('ix_players_player_code'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_code'), table_name='games')
    op.drop_index(op.f('ix_games_date'), table_name='games')
    op.drop_index(op.f('ix_games_away_team_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_team_code'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
